version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=scrumee
      - MYSQL_DATABASE=scrumee
      - MYSQL_USER=root
      - MYSQL_PASSWORD=scrumee
