# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    # Guzzle Client Factory
    guzzle_client.factory:
        class: Scrumee\ApiBundle\Client\ClientFactory

    # API Serializer
    api_serializer:
        class: Scrumee\ApiBundle\Serializer\Serializer

    # API Client (created using the factory method)
    api_client:
        class: Scrumee\ApiBundle\Client\JiraClient
        factory: ['@guzzle_client.factory', createJiraClient]
        arguments: ['%guzzle_api.options%', '%jira_api.parameters%']

    # API Finder
    api_finder:
        class: Scrumee\ApiBundle\Finder\Finder
        arguments: ['@api_client']

    # API Manager
    api_manager:
        abstract: true
        class: Scrumee\ApiBundle\Manager\AbstractManager
        arguments: ['@api_finder', '@api_serializer']

    # Jira Project Manager
    jira_manager.project:
        parent: api_manager
        class: Scrumee\ApiBundle\Manager\Jira\ProjectManager

    # Jira Sprint Manager
    jira_manager.sprint:
        parent: api_manager
        class: Scrumee\ApiBundle\Manager\Jira\SprintManager

    # Jira Issue Manager
    jira_manager.issue:
        parent: api_manager
        class: Scrumee\ApiBundle\Manager\Jira\IssueManager

    # Jira XBoard
    jira_manager.xboard:
        parent: api_manager
        class: Scrumee\ApiBundle\Manager\GreenHooper\XBoardManager
